language: php

php:
  - 5.4
  - 5.6
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer update

script:
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - slps970093@gmail.com
    on_success: always
    on_failure: always